Metadata:
  ProcessAccountsStateMachine:
    localTemplateFile: &process_accounts_state_machine_body ./src/state-machines/ProcessAccounts/machine.asl.json

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Collect resources from AWS accounts

Parameters:
  Domain:
    Type: String
    Description: 'Application Domain'

  System:
    Type: String
    Description: 'Application System'

  Component:
    Type: String
    Description: 'Application Component'

  CodeBranch:
    Type: String
    Description: "Name of deployment branch"

  CatalogEndpoint:
    Type: String
    Description: "Catalog endpoint"

  ClientId:
    Type: String
    Description: "Client ID"
    NoEcho: true

  ClientSecret:
    Type: String
    Description: "Client Secret"
    NoEcho: true

  CrossAccountRoleName:
    Type: String
    Description: "Cross account role name"

  AwsOrganizationId:
    Type: String
    Description: "AWS Organization ID"

Resources:
  # EventBridge
  AwsResourceCollectorDlq:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days
      VisibilityTimeout: 300 # 5 minutes

  AwsResourceCollectorDlqPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref AwsResourceCollectorDlq
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt AwsResourceCollectorDlq.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt AwsResourceCollectorBus.Arn

  AwsResourceCollectorBus:
    Type: AWS::Events::EventBus
    Properties:
      Name: !Sub "${AWS::StackName}-AwsResourceCollectorBus"
      Policy:
        Version: '2012-10-17'
        Statement:
          - Sid: CrossAccountAllowPutEvents
            Effect: Allow
            Principal: '*'
            Action:
              - events:PutEvents
            Resource: "*"
            Condition:
              StringEquals:
                "aws:PrincipalOrgID": !Ref AwsOrganizationId
      DeadLetterConfig:
        Arn: !GetAtt AwsResourceCollectorDlq.Arn
