AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: |
  Collect resources from AWS accounts

Parameters:
  Domain:
    Type: String
    Description: 'Application Domain'

  System:
    Type: String
    Description: 'Application System'

  Component:
    Type: String
    Description: 'Application Component'

  CodeBranch:
    Type: String
    Description: "Name of deployment branch"

  ClientId:
    Type: String
    Description: "Client ID"
    NoEcho: true

  ClientSecret:
    Type: String
    Description: "Client Secret"
    NoEcho: true

Globals:
  Function:
    Runtime: python3.13
    MemorySize: 128
    Environment:
      Variables:
        POWERTOOLS_SERVICE_NAME: !Ref AWS::StackName


Resources:
  # Functions
  ListAccountsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handlers/ListAccounts
      Handler: function.handler
      Description: List AWS accounts
      Timeout: 15
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: rate(15 minutes)
      Policies:
        - SQSSendMessagePolicy:
            QueueName: !GetAtt DestinationSqsQueue.QueueName
        - AWSOrganizationsReadOnlyAccess
      Environment:
        Variables:
          SQS_QUEUE_URL: !GetAtt DestinationSqsQueue.QueueUrl

  AddAccountToCatalogFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/handlers/AddAccountToCatalog
      Handler: function.handler
      Description: Add account to catalog
      Timeout: 5
      Environment:
        Variables:
          CLIENT_ID: !Ref ClientId
          CLIENT_SECRET: !Ref ClientSecret
      Policies:
        - SQSPollerPolicy:
            QueueName: !GetAtt DestinationSqsQueue.QueueName
      Events:
        Sqs:
          Type: SQS
          Properties:
            Queue: !GetAtt DestinationSqsQueue.Arn
            BatchSize: 10

  DestinationSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      VisibilityTimeout: 120
      MessageRetentionPeriod: 300   # Go away before next invocation of ListAccountsFunction