AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Cross-account role for AWS Resource Collector

Parameters:
  CollectorAccounts:
    Type: CommaDelimitedList
    Description: Comma separated list of OUs

  AwsOrganizationId:
    Type: String
    Description: AWS Organization ID

  CrossAccountRoleName:
    Type: String
    Description: Name of the cross-account role

Resources:
  CrossAccountRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Ref CrossAccountRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            # Really should be scoped to a specific role but I suspect we'll end up with many
            # roles, one per resource type, so this is I think fine from a long-term view.
            # However the condition must never be deleted!
            Principal:
              AWS: '*'
            Action:
              - sts:AssumeRole
              - sts:TagSession
            # WARNING: This is a critical condition that must never be removed!
            Condition:
              StringEquals:
                "aws:PrincipalOrgID":
                  - !Ref AwsOrganizationId
                "aws:PrincipalAccount": !Ref CollectorAccounts

      Policies:
        - PolicyName: DescribeCfnStacks
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStack*
                Resource: "*"
        - PolicyName: DescribeEcs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecs:ListClusters
                  - ecs:DescribeClusters
                  - ecs:ListTagsForResource
                Resource: "*"
        - PolicyName: DescribeVpcs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ec2:DescribeVpcs
                Resource: "*"
        - PolicyName: DescribeS3Buckets
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:listallmybuckets
                  - s3:GetBucketTagging
                Resource: "*"