AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Cross-account role for AWS Resource Collector

Parameters:
  AwsResourceCollectorBusArn:
    Type: String
    Description: ARN of eventbus to forward events to.

Resources:
  ResourceChangeEventsFowardingIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: EventBridgeForwardingRulePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !Ref AwsResourceCollectorBusArn

  ResourceChangeEventsFowardingRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Forward AWS resource Creation and Deletion events to central eventbus.
      EventPattern:
        source:
          - prefix: "aws."
        detail:
          eventName:
            - prefix: "Create"
            - prefix: "Delete"
      RoleArn: !GetAtt ResourceChangeEventsFowardingIamRole.Arn
      Targets:
        - Id: AwsResourceCollectorBus
          Arn: !Ref AwsResourceCollectorBusArn
