AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Cross-account role for AWS Resource Collector

Parameters:
  AwsResourceCollectorBusArn:
    Type: String
    Description: ARN of eventbus to forward events to.

Resources:
  ResourceChangeEventsFowardingRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Forward AWS resource Creation and Deletion events to central eventbus.
      EventPattern:
        source:
          - prefix: "aws."
        detail:
          eventName:
            - prefix: "Create"
            - prefix: "Delete"
      Targets:
        - Id: AwsResourceCollectorBus
          Arn: !Ref AwsResourceCollectorBusArn
