AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Cross-account role for AWS Resource Collector

Parameters:
  AwsResourceCollectorBusArn:
    Type: String
    Description: ARN of eventbus to forward events to.

Resources:
  ResourceChangeEventsFowardingIamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: EventBridgeForwardingRulePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - events:PutEvents
                Resource: !Ref AwsResourceCollectorBusArn

  TargetDlq:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600 # 14 days
      VisibilityTimeout: 300 # 5 minutes

  TargetDlqPolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref TargetDlq
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sqs:SendMessage
            Resource: !GetAtt TargetDlq.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt ResourceChangeEventsFowardingRule.Arn

  ResourceChangeEventsFowardingRule:
    Type: AWS::Events::Rule
    Properties:
      Description: Forward AWS resource Creation and Deletion events to central eventbus.
      EventPattern:
        source:
          - "aws.ec2"
          - "aws.ecs"
          - "aws.s3"
        detail:
          eventName:
            - prefix: "Create"
            - prefix: "Delete"
      Targets:
        - Id: AwsResourceCollectorBus
          Arn: !Ref AwsResourceCollectorBusArn
          RoleArn: !GetAtt ResourceChangeEventsFowardingIamRole.Arn
          DeadLetterConfig:
            Arn: !GetAtt TargetDlq.Arn
